image: Ubuntu1804  # образ для сборки

environment:
  name: 
  nodejs_version: "18"

branches:
  only:
    - main  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

test_script:

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose